<?php

return [
    'en_to_es' => [

        // --- Proteínas ---
        'chicken' => 'pollo',
        'chicken breast' => 'pechuga de pollo',
        'chicken breasts' => 'pechugas de pollo',
        'chicken thighs' => 'muslos de pollo',
        'beef' => 'ternera',
        'minced beef' => 'carne picada de ternera',
        'mixed beef cuts' => 'cortes de ternera mixtos',
        'pork' => 'cerdo',
        'morcilla' => 'morcilla',
        'bacon' => 'bacon',
        'mussels' => 'mejillones',
        'raw tiger prawns' => 'langostinos tigre crudos',
        'squid' => 'calamar',
        'chicken liver' => 'hígado de pollo',

        // --- Lácteos y derivados ---
        'milk' => 'leche',
        'cream cheese' => 'queso crema',
        'mozzarella' => 'mozzarella',
        'mozzarella balls' => 'bolitas de mozzarella',
        'parmesan cheese' => 'queso parmesano',
        'cheese' => 'queso',
        'butter' => 'mantequilla',
        'unsalted butter' => 'mantequilla sin sal',
        'greek yogurt' => 'yogur griego',
        'natural yoghurt' => 'yogur natural',
        'creme fraiche' => 'crema fresca',
        'dulce de leche' => 'dulce de leche',

        // --- Verduras y hortalizas ---
        'onion' => 'cebolla',
        'chopped onion' => 'cebolla picada',
        'spring onions' => 'cebolletas',
        'green pepper' => 'pimiento verde',
        'red pepper' => 'pimiento rojo',
        'romano pepper' => 'pimiento romano',
        'carrots' => 'zanahorias',
        'potatoes' => 'patatas',
        'cucumber' => 'pepino',
        'beetroot' => 'remolacha',
        'white cabbage' => 'col blanca',
        'pumpkin' => 'calabaza',
        'mushrooms' => 'champiñones',
        'lentils' => 'lentejas',
        'brown lentils' => 'lentejas pardinas',
        'broad beans' => 'habas',
        'kidney beans' => 'alubias rojas',
        'dried white beans' => 'alubias blancas secas',
        'dried white corn' => 'maíz blanco seco',

        // --- Frutas ---
        'lemon' => 'limón',
        'lemon juice' => 'zumo de limón',
        'lemon zest' => 'ralladura de limón',
        'raisins' => 'pasas',
        'prunes' => 'ciruelas pasas',
        'pomegranate molasses' => 'melaza de granada',

        // --- Hierbas y especias ---
        'parsley' => 'perejil',
        'basil leaves' => 'hojas de albahaca',
        'mint' => 'menta',
        'dried mint' => 'menta seca',
        'thyme' => 'tomillo',
        'coriander' => 'cilantro',
        'cilantro' => 'cilantro',
        'bay leaf' => 'hoja de laurel',
        'garlic' => 'ajo',
        'garlic clove' => 'diente de ajo',
        'garlic powder' => 'ajo en polvo',
        'ginger' => 'jengibre',
        'cumin' => 'comino',
        'ground cumin' => 'comino molido',
        'cumin seeds' => 'semillas de comino',
        'mustard' => 'mostaza',
        'mustard seeds' => 'semillas de mostaza',
        'paprika' => 'pimentón',
        'red pepper flakes' => 'copos de chile rojo',
        'red chilli flakes' => 'copos de chile rojo',
        'cayenne pepper' => 'pimienta de cayena',
        'turmeric' => 'cúrcuma',
        'black pepper' => 'pimienta negra',
        'pepper' => 'pimienta',
        'sumac' => 'zumaque',
        'pul biber' => 'chile turco',
        'saffron' => 'azafrán',
        'garam masala' => 'garam masala',
        'kabse spice' => 'especias kabsa',

        // --- Aceites, grasas y condimentos ---
        'olive oil' => 'aceite de oliva',
        'extra virgin olive oil' => 'aceite de oliva virgen extra',
        'sunflower oil' => 'aceite de girasol',
        'vegetable oil' => 'aceite vegetal',
        'oil' => 'aceite',
        'soy sauce' => 'salsa de soja',
        'mayonnaise' => 'mayonesa',
        'honey' => 'miel',
        'rose water' => 'agua de rosas',
        'white wine vinegar' => 'vinagre de vino blanco',
        'rice wine' => 'vino de arroz',
        'sea salt' => 'sal marina',
        'salt' => 'sal',

        // --- Harinas, masas y panes ---
        'flour' => 'harina',
        'corn flour' => 'harina de maíz',
        'chickpea flour' => 'harina de garbanzo',
        'strong white bread flour' => 'harina de fuerza',
        'yeast' => 'levadura',
        'baking powder' => 'levadura química',
        'bread' => 'pan',
        'crusty bread' => 'pan crujiente',
        'filo pastry' => 'masa filo',
        'lasagne sheets' => 'láminas de lasaña',
        'macaroni' => 'macarrones',

        // --- Arroz, pasta y cereales ---
        'rice' => 'arroz',
        'sushi rice' => 'arroz para sushi',
        'paella rice' => 'arroz para paella',

        // --- Tomate y derivados ---
        'tomato' => 'tomate',
        'chopped tomatoes' => 'tomate troceado',
        'tinned tomatos' => 'tomates enlatados',
        'tomato puree' => 'puré de tomate',

        // --- Otros ---
        'water' => 'agua',
        'sugar' => 'azúcar',
        'caster sugar' => 'azúcar glas',
        'knafeh' => 'kunafa',
        'tahini paste' => 'pasta de tahini',
        'beef gravy' => 'salsa de carne',
        'cheese curds' => 'cuajada de queso',
    ],

    'es_to_en' => [

        // --- A ---
        'aceite' => 'oil',
        'aceite de girasol' => 'sunflower oil',
        'aceite de oliva' => 'olive oil',
        'aceite de oliva virgen extra' => 'extra virgin olive oil',
        'aceite vegetal' => 'vegetable oil',
        'agua' => 'water',
        'ajo' => 'garlic',
        'ajo en polvo' => 'garlic powder',
        'albahaca' => 'basil leaves',
        'alubias blancas secas' => 'dried white beans',
        'alubias rojas' => 'kidney beans',
        'arroz' => 'rice',
        'arroz para paella' => 'paella rice',
        'arroz para sushi' => 'sushi rice',
        'azafrán' => 'saffron',
        'azúcar' => 'sugar',
        'azúcar glas' => 'caster sugar',

        // --- B ---
        'bacon' => 'bacon',
        'calabaza' => 'pumpkin',
        'caldo vegetal' => 'vegetable stock',
        'canela' => 'cinnamon',
        'carne picada de ternera' => 'minced beef',
        'cebolla' => 'onion',
        'cebolla picada' => 'chopped onion',
        'cebolletas' => 'spring onions',
        'cerdo' => 'pork',
        'champiñones' => 'mushrooms',
        'chile turco' => 'pul biber',
        'chile verde' => 'green chilli',
        'chorizo' => 'chorizo',
        'ciruelas pasas' => 'prunes',
        'cilantro' => 'cilantro',
        'coco' => 'coconut',
        'col blanca' => 'white cabbage',
        'comino' => 'cumin',
        'comino molido' => 'ground cumin',
        'copos de chile rojo' => 'red pepper flakes',
        'cortes de ternera mixtos' => 'mixed beef cuts',
        'crema fresca' => 'creme fraiche',
        'crema de queso' => 'cream cheese',
        'cúrcuma' => 'turmeric',

        // --- D ---
        'diente de ajo' => 'garlic clove',
        'dulce de leche' => 'dulce de leche',

        // --- E ---
        'eneldo' => 'dill',
        'especias kabsa' => 'kabse spice',
        'espinacas' => 'spinach',
        'fideos macarrones' => 'macaroni',

        // --- G ---
        'gambas' => 'prawns',
        'garbanzos' => 'chickpeas',
        'ghee' => 'ghee',
        'guisantes amarillos partidos' => 'toor dal',

        // --- H ---
        'habas' => 'broad beans',
        'harina' => 'flour',
        'harina de fuerza' => 'strong white bread flour',
        'harina de garbanzo' => 'chickpea flour',
        'harina de maíz' => 'corn flour',
        'higo' => 'fig',
        'hinojo' => 'fennel',
        'hoja de laurel' => 'bay leaf',
        'hojas de albahaca' => 'basil leaves',
        'huevo' => 'egg',
        'yemas de huevo' => 'egg yolks',
        'hígado de pollo' => 'chicken liver',


        // --- J ---
        'jarrete de ternera' => 'beef shin',
        'jengibre' => 'ginger',

        // --- L ---
        'langostinos tigre crudos' => 'raw tiger prawns',
        'lechuga iceberg' => 'iceberg lettuce',
        'leche' => 'milk',
        'leche de coco' => 'coconut milk',
        'leche evaporada' => 'evaporated milk',
        'limón' => 'lemon',
        'zumo de limón' => 'lemon juice',
        'ralladura de limón' => 'lemon zest',
        'lentejas' => 'lentils',
        'lentejas pardinas' => 'brown lentils',

        // --- M ---
        'maíz blanco seco' => 'dried white corn',
        'maíz dulce' => 'sweetcorn',
        'masa filo' => 'filo pastry',
        'mantequilla' => 'butter',
        'mantequilla sin sal' => 'unsalted butter',
        'melaza de granada' => 'pomegranate molasses',
        'menta' => 'mint',
        'menta seca' => 'dried mint',
        'miel' => 'honey',
        'mozzarella' => 'mozzarella',
        'bolitas de mozzarella' => 'mozzarella balls',
        'morcilla' => 'morcilla',

        // --- P ---
        'pan' => 'bread',
        'pan crujiente' => 'crusty bread',
        'pan de hamburguesa con sésamo' => 'sesame seed burger buns',
        'pasta de tahini' => 'tahini paste',
        'patatas' => 'potatoes',
        'perejil' => 'parsley',
        'pimiento rojo' => 'red pepper',
        'pimiento verde' => 'green pepper',
        'pimiento romano' => 'romano pepper',
        'pimienta' => 'pepper',
        'pimienta negra' => 'black pepper',
        'pimienta de cayena' => 'cayenne pepper',
        'pollo' => 'chicken',
        'puré de tomate' => 'tomato puree',

        // --- Q ---
        'queso' => 'cheese',
        'queso crema' => 'cream cheese',
        'queso parmesano' => 'parmesan cheese',
        'cuajada de queso' => 'cheese curds',

        // --- R ---
        'remolacha' => 'beetroot',
        'romero' => 'rosemary',

        // --- S ---
        'sal' => 'salt',
        'sal marina' => 'sea salt',
        'salsa de carne' => 'beef gravy',
        'salsa de soja' => 'soy sauce',
        'semillas de amapola' => 'poppy seeds',
        'semillas de comino' => 'cumin seeds',
        'semillas de mostaza' => 'mustard seeds',
        'tomate' => 'tomato',
        'tomate troceado' => 'chopped tomatoes',
        'tomates enlatados' => 'tinned tomatos',

        // --- T ---
        'tomillo' => 'thyme',
        'turco chile' => 'pul biber',

        // --- V ---
        'vainilla' => 'vanilla',
        'vaina de vainilla' => 'vanilla pod',
        'vinagre de vino blanco' => 'white wine vinegar',
        'vino de arroz' => 'rice wine',

    ],

    'categorias' => [
        'beef' => 'ternera',
        'breakfast' => 'desayuno',
        'chicken' => 'pollo',
        'dessert' => 'postre',
        'goat' => 'cabra',
        'lamb' => 'cordero',
        'miscellaneous' => 'misceláneo',
        'pasta' => 'pasta',
        'pork' => 'cerdo',
        'seafood' => 'mariscos',
        'side' => 'acompañamiento',
        'starter' => 'entrante',
        'vegan' => 'vegano',
        'vegetarian' => 'vegetariano',
    ],

    'cocinas' => [
        'british' => 'británica',
        'canadian' => 'canadiense',
        'chinese' => 'china',
        'croatian' => 'croata',
        'dutch' => 'holandesa',
        'egyptian' => 'egipcia',
        'french' => 'francesa',
        'greek' => 'griega',
        'indian' => 'india',
        'irish' => 'irlandesa',
        'italian' => 'italiana',
        'jamaican' => 'jamaicana',
        'japanese' => 'japonesa',
        'kenyan' => 'keniana',
        'malaysian' => 'malasia',
        'mexican' => 'mexicana',
        'moroccan' => 'marroquí',
        'polish' => 'polaca',
        'portuguese' => 'portuguesa',
        'russian' => 'rusa',
        'spanish' => 'española',
        'thai' => 'tailandesa',
        'tunisian' => 'tunecina',
        'turkish' => 'turca',
        'vietnamese' => 'vietnamita',
    ],
];
