<?php

return [

    'chicken' => 'Pollo',
    'beef' => 'Ternera',
    'pork' => 'Cerdo',
    'lamb' => 'Cordero',
    'turkey' => 'Pavo',

    'rice' => 'Arroz',
    'pasta' => 'Pasta',
    'bread' => 'Pan',
    'flour' => 'Harina',
    'potato' => 'Patata',
    'sweet potato' => 'Boniato',

    'tomato' => 'Tomate',
    'onion' => 'Cebolla',
    'garlic' => 'Ajo',
    'carrot' => 'Zanahoria',
    'pepper' => 'Pimiento',
    'lettuce' => 'Lechuga',
    'spinach' => 'Espinacas',
    'mushroom' => 'Champiñón',
    'apple' => 'Manzana',
    'banana' => 'Plátano',
    'orange' => 'Naranja',
    'lemon' => 'Limón',
    'lime' => 'Lima',
    'strawberry' => 'Fresa',
    'grape' => 'Uva',
    'watermelon' => 'Sandía',
    'pineapple' => 'Piña',
    'mango' => 'Mango',
    'peach' => 'Melocotón',
    'pear' => 'Pera',
    'cherry' => 'Cereza',
    'blueberry' => 'Arándano',
    'raspberry' => 'Frambuesa',
    'blackberry' => 'Zarzamora',
    'kiwi' => 'Kiwi',
    'avocado' => 'Aguacate',

    'milk' => 'Leche',
    'cheese' => 'Queso',
    'butter' => 'Mantequilla',
    'cream' => 'Nata',
    'egg' => 'Huevo',
    'yogurt' => 'Yogur',

    'olive oil' => 'Aceite de oliva',
    'salt' => 'Sal',
    'sugar' => 'Azúcar',
    'pepper black' => 'Pimienta negra',
    'vinegar' => 'Vinagre',

];
