<?php

return [
    'en_to_es' => [
        'chicken' => 'pollo',
        'salmon' => 'salmon',
        'beef' => 'ternera',
        'pork' => 'cerdo',
        'lamb' => 'cordero',
        'avocado' => 'aguacate',
        'apple cider vinegar' => 'vinagre de sidra de manzana',
        'apple' => 'manzana',
        'almond milk' => 'leche de almendras',
        'anchovies' => 'anchoas',
        'artichoke' => 'alcachofa',
        'asparagus' => 'esparragos',
        'aubergine' => 'berenjena',
        'bacon' => 'bacon',
        'chicken liver' => 'higado de pollo',
        'liver pate' => 'paté de hígado',
        'baking powder' => 'levadura quimica',
        'baking soda' => 'bicarbonato',
        'banana' => 'platano',
        'basil' => 'albahaca',
        'bay leaf' => 'hoja de laurel',
        'beans' => 'alubias',
        'beetroot' => 'remolacha',
        'bell pepper' => 'pimiento',
        'black beans' => 'alubias negras',
        'black olives' => 'aceitunas negras',
        'black pepper' => 'pimienta negra',
        'blue cheese' => 'queso azul',
        'bread' => 'pan',
        'breadcrumbs' => 'pan rallado',
        'broccoli' => 'brocoli',
        'brown sugar' => 'azucar moreno',
        'butter' => 'mantequilla',
        'cabbage' => 'col',
        'cajun seasoning' => 'condimento cajun',
        'canned tomatoes' => 'tomates enlatados',
        'capers' => 'alcaparras',
        'carrot' => 'zanahoria',
        'cashews' => 'anacardos',
        'cauliflower' => 'coliflor',
        'celery' => 'apio',
        'cheddar cheese' => 'queso cheddar',
        'cherry tomatoes' => 'tomates cherry',
        'chickpeas' => 'garbanzos',
        'chili powder' => 'chile en polvo',
        'chili flakes' => 'copos de chile',
        'chives' => 'cebollino',
        'chocolate' => 'chocolate',
        'cilantro' => 'cilantro',
        'cinnamon' => 'canela',
        'cloves' => 'clavos',
        'coconut milk' => 'leche de coco',
        'coconut oil' => 'aceite de coco',
        'cod' => 'bacalao',
        'coffee' => 'cafe',
        'corn' => 'maiz',
        'corn flour' => 'harina de maiz',
        'cornstarch' => 'maicena',
        'couscous' => 'cuscus',
        'cream' => 'nata',
        'cream cheese' => 'queso crema',
        'cucumber' => 'pepino',
        'cumin' => 'comino',
        'currants' => 'grosellas',
        'curry powder' => 'curry en polvo',
        'dates' => 'dátiles',
        'dill' => 'eneldo',
        'duck' => 'pato',
        'egg' => 'huevo',
        'eggplant' => 'berenjena',
        'evaporated milk' => 'leche evaporada',
        'feta cheese' => 'queso feta',
        'figs' => 'higos',
        'fish sauce' => 'salsa de pescado',
        'flour' => 'harina',
        'garlic' => 'ajo',
        'garlic powder' => 'ajo en polvo',
        'ginger' => 'jengibre',
        'goat cheese' => 'queso de cabra',
        'grapes' => 'uvas',
        'green beans' => 'judias verdes',
        'green olives' => 'aceitunas verdes',
        'green onion' => 'cebolla verde',
        'ground beef' => 'carne picada de ternera',
        'ground pork' => 'carne picada de cerdo',
        'ham' => 'jamon',
        'hazelnuts' => 'avellanas',
        'honey' => 'miel',
        'hot sauce' => 'salsa picante',
        'kale' => 'col rizada',
        'ketchup' => 'ketchup',
        'kidney beans' => 'alubias rojas',
        'leek' => 'puerro',
        'lemon' => 'limon',
        'lemon juice' => 'zumo de limon',
        'lentils' => 'lentejas',
        'lettuce' => 'lechuga',
        'lime' => 'lima',
        'lime juice' => 'zumo de lima',
        'lobster' => 'langosta',
        'mango' => 'mango',
        'maple syrup' => 'sirope de arce',
        'mayonnaise' => 'mayonesa',
        'milk' => 'leche',
        'mint' => 'menta',
        'minced beef' => 'carne picada de ternera',
        'chicken breasts' => 'pechugas de pollo',
        'chicken breast' => 'pechuga de pollo',
        'chicken thighs' => 'muslos de pollo',
        'mussels' => 'mejillones',
        'spaghetti' => 'espaguetis',
        'mozzarella' => 'mozzarella',
        'mushroom' => 'champiñon',
        'mustard' => 'mostaza',
        'nutmeg' => 'nuez moscada',
        'oats' => 'avena',
        'olive oil' => 'aceite de oliva',
        'onion' => 'cebolla',
        'orange' => 'naranja',
        'oregano' => 'oregano',
        'paprika' => 'pimenton',
        'parmesan' => 'parmesano',
        'parsley' => 'perejil',
        'pasta' => 'pasta',
        'peanut butter' => 'mantequilla de cacahuete',
        'peanuts' => 'cacahuetes',
        'pear' => 'pera',
        'peas' => 'guisantes',
        'pecans' => 'nueces pecanas',
        'pepper' => 'pimienta',
        'pineapple' => 'piña',
        'pistachios' => 'pistachos',
        'plum' => 'ciruela',
        'pomegranate' => 'granada',
        'pork chops' => 'chuletas de cerdo',
        'potato' => 'patata',
        'prawns' => 'gambas',
        'pumpkin' => 'calabaza',
        'quinoa' => 'quinoa',
        'raisins' => 'pasas',
        'raspberries' => 'frambuesas',
        'red cabbage' => 'col lombarda',
        'red onion' => 'cebolla roja',
        'red pepper' => 'pimiento rojo',
        'rice' => 'arroz',
        'rice vinegar' => 'vinagre de arroz',
        'ricotta' => 'ricotta',
        'rosemary' => 'romero',
        'rum' => 'ron',
        'sage' => 'salvia',
        'salt' => 'sal',
        'sardines' => 'sardinas',
        'sausage' => 'salchicha',
        'scallions' => 'cebolletas',
        'sesame oil' => 'aceite de sesamo',
        'sesame seeds' => 'semillas de sesamo',
        'shallots' => 'chalotas',
        'shrimp' => 'langostinos',
        'smoked paprika' => 'pimenton ahumado',
        'sour cream' => 'crema agria',
        'soy sauce' => 'salsa de soja',
        'spinach' => 'espinacas',
        'spring onion' => 'cebolla tierna',
        'squash' => 'calabacin',
        'squid' => 'calamar',
        'steak' => 'filete',
        'strawberries' => 'fresas',
        'sugar' => 'azucar',
        'sunflower oil' => 'aceite de girasol',
        'sweet potato' => 'batata',
        'sweetcorn' => 'maiz dulce',
        'tahini' => 'tahini',
        'tarragon' => 'estragon',
        'thyme' => 'tomillo',
        'tofu' => 'tofu',
        'tomato' => 'tomate',
        'tomato paste' => 'pasta de tomate',
        'tomato sauce' => 'salsa de tomate',
        'tortilla' => 'tortilla',
        'tuna' => 'atun',
        'turmeric' => 'curcuma',
        'vanilla' => 'vainilla',
        'vegetable broth' => 'caldo de verduras',
        'vegetable oil' => 'aceite vegetal',
        'vinegar' => 'vinagre',
        'walnuts' => 'nueces',
        'water' => 'agua',
        'wheat flour' => 'harina de trigo',
        'white chocolate' => 'chocolate blanco',
        'white pepper' => 'pimienta blanca',
        'white wine' => 'vino blanco',
        'whole milk' => 'leche entera',
        'wine' => 'vino',
        'worcestershire sauce' => 'salsa worcestershire',
        'yeast' => 'levadura',
        'yogurt' => 'yogur',
        'zucchini' => 'calabacin',
        'almonds' => 'almendras',
        'apricot' => 'albaricoque',
        'arugula' => 'rúcula',
        'basil leaves' => 'hojas de albahaca',
        'beef broth' => 'caldo de ternera',
        'blueberries' => 'arándanos',
        'brandy' => 'brandy',
        'brown rice' => 'arroz integral',
        'buttermilk' => 'suero de leche',
        'cacao powder' => 'cacao en polvo',
        'cane sugar' => 'azucar de caña',
        'cardamom' => 'cardamomo',
        'cayenne pepper' => 'pimienta de cayena',
        'cheese' => 'queso',
        'cherry' => 'cereza',
        'chili' => 'chile',
        'clotted cream' => 'nata coagulada',
        'cocoa powder' => 'cacao en polvo',
        'coconut' => 'coco',
        'coriander' => 'cilantro',
        'cranberries' => 'arándanos rojos',
        'cream of tartar' => 'cremor tártaro',
        'croutons' => 'picatostes',
        'cumin seeds' => 'semillas de comino',
        'duck fat' => 'grasa de pato',

        'beef stock' => 'caldo de ternera',
        'chicken stock' => 'caldo de pollo',
        'fish' => 'pescado',
        'crab' => 'cangrejo',
        'clam' => 'almeja',
        'scallops' => 'vieiras',
        'trout' => 'trucha',
        'haddock' => 'eglefino',
        'tilapia' => 'tilapia',
        'smoked salmon' => 'salmon ahumado',
        'broth' => 'caldo',
        'penne' => 'macarrones',
        'lasagna noodles' => 'laminas de lasaña',
        'risotto rice' => 'arroz para risotto',
        'barley' => 'cebada',

        'double cream' => 'nata doble',
        'whipping cream' => 'nata para montar',
        'condensed milk' => 'leche condensada',

        'green pepper' => 'pimiento verde',
        'yellow pepper' => 'pimiento amarillo',
        'parsley root' => 'raíz de perejil',
        'shallot' => 'chalota',

        'garam masala' => 'garam masala',
        'five spice' => 'cinco especias',
        'coriander seeds' => 'semillas de cilantro',
        'cardamom pods' => 'vainas de cardamomo',
        'bay leaves' => 'hojas de laurel',
        'pimenton ahumado' => 'smoked paprika',

        'black-eyed peas' => 'frijoles carita',
        'split peas' => 'guisantes partidos',

        'raspberry' => 'frambuesa',
        'blueberry' => 'arándano',
        'grapefruit' => 'pomelo',
        'peach' => 'melocotón',


    ],

    'es_to_en' => [

        // CARNES Y PESCADOS
        'pollo' => 'chicken',
        'pechuga de pollo' => 'chicken breast',
        'pechugas de pollo' => 'chicken breasts',
        'muslos de pollo' => 'chicken thighs',
        'cordero' => 'lamb',
        'ternera' => 'beef',
        'carne picada de ternera' => 'minced beef',
        'cerdo' => 'pork',
        'carne picada de cerdo' => 'ground pork',
        'salmon' => 'salmon',
        'bacalao' => 'cod',
        'pato' => 'duck',
        'jamon' => 'ham',
        'jamón' => 'ham',
        'langosta' => 'lobster',
        'ostras' => 'oysters',
        'mejillones' => 'mussels',
        'pekín' => 'peking duck',
        'higado de pollo' => 'chicken liver',
        'paté de hígado' => 'liver pate',
        'caldo de ternera' => 'beef stock',
        'caldo de pollo' => 'chicken stock',
        'pescado' => 'fish',
        'cangrejo' => 'crab',
        'almeja' => 'clam',
        'vieiras' => 'scallops',
        'trucha' => 'trout',
        'eglefino' => 'haddock',
        'tilapia' => 'tilapia',
        'salmon ahumado' => 'smoked salmon',




        // PASTA, ARROZ Y CEREALES
        'espaguetis' => 'spaghetti',
        'pasta' => 'pasta',
        'arroz' => 'rice',
        'arroz basmati' => 'basmati rice',
        'arroz integral' => 'brown rice',
        'fideos' => 'noodles',
        'cuscus' => 'couscous',
        'fideos de arroz' => 'rice noodles',
        'vermicelli de arroz' => 'rice vermicelli',

        'macarrones' => 'penne',
        'laminas de lasaña' => 'lasagna noodles',
        'arroz para risotto' => 'risotto rice',
        'quinoa' => 'quinoa',
        'cebada' => 'barley',


        // LÁCTEOS
        'mantequilla' => 'butter',
        'nata' => 'cream',
        'queso crema' => 'cream cheese',
        'queso feta' => 'feta cheese',
        'mozzarella' => 'mozzarella',
        'queso cheddar' => 'cheddar cheese',
        'queso azul' => 'blue cheese',
        'queso de cabra' => 'goat cheese',
        'leche' => 'milk',
        'leche evaporada' => 'evaporated milk',
        'yogur' => 'yogurt',
        'parmesano' => 'parmesan cheese',

        'nata doble' => 'double cream',
        'nata para montar' => 'whipping cream',
        'leche condensada' => 'condensed milk',
        'suero de leche' => 'buttermilk',


        // VERDURAS Y HORTALIZAS
        'aguacate' => 'avocado',
        'alcachofa' => 'artichoke',
        'esparragos' => 'asparagus',
        'espinacas' => 'spinach',
        'berenjena' => 'eggplant',
        'brocoli' => 'broccoli',
        'col' => 'cabbage',
        'zanahoria' => 'carrot',
        'coliflor' => 'cauliflower',
        'apio' => 'celery',
        'pepino' => 'cucumber',
        'pimiento' => 'bell pepper',
        'pimientos' => 'peppers',
        'cebolla' => 'onion',
        'cebolla verde' => 'green onion',
        'lechuga' => 'lettuce',
        'champiñones' => 'mushroom',
        'guisantes' => 'peas',
        'tomates cherry' => 'cherry tomatoes',

        'pimiento verde' => 'green pepper',
        'pimiento rojo' => 'red pepper',
        'pimiento amarillo' => 'yellow pepper',
        'col rizada' => 'kale',
        'raiz de perejil' => 'parsley root',
        'cebolla tierna' => 'spring onion',
        'chalota' => 'shallot',



        // LEGUMBRES
        'alubias' => 'beans',
        'alubias negras' => 'black beans',
        'alubias rojas' => 'kidney beans',
        'garbanzos' => 'chickpeas',
        'lentejas' => 'lentils',

        'frijoles carita' => 'black-eyed peas',
        'guisantes partidos' => 'split peas',



        // FRUTAS
        'platano' => 'banana',
        'uvas' => 'grapes',
        'higos' => 'figs',
        'limon' => 'lemon',
        'zumo de limon' => 'lemon juice',
        'lima' => 'lime',
        'zumo de lima' => 'lime juice',
        'mango' => 'mango',
        'naranja' => 'orange',
        'piña' => 'pineapple',
        'granada' => 'pomegranate',

        'frambuesa' => 'raspberry',
        'arándano' => 'blueberry',
        'pomelo' => 'grapefruit',
        'melocotón' => 'peach',




        // HIERBAS Y ESPECIAS
        'albahaca' => 'basil',
        'hoja de laurel' => 'bay leaf',
        'chile en polvo' => 'chili powder',
        'copos de chile' => 'chili flakes',
        'cebollino' => 'chives',
        'cilantro' => 'cilantro',
        'canela' => 'cinnamon',
        'clavos' => 'cloves',
        'comino' => 'cumin',
        'curry en polvo' => 'curry powder',
        'eneldo' => 'dill',
        'jengibre' => 'ginger',
        'menta' => 'mint',
        'organo' => 'oregano',
        'perejil' => 'parsley',
        'pimienta negra' => 'black pepper',
        'pimenton' => 'paprika',

        'garam masala' => 'garam masala',
        'cinco especias' => 'five spice',
        'semillas de cilantro' => 'coriander seeds',
        'vainas de cardamomo' => 'cardamom pods',
        'hojas de laurel' => 'bay leaves',




        // OTROS
        'vinagre de sidra de manzana' => 'apple cider vinegar',
        'leche de almendras' => 'almond milk',
        'anchoas' => 'anchovies',
        'bacon' => 'bacon',
        'levadura quimica' => 'baking powder',
        'bicarbonato' => 'baking soda',
        'pan' => 'bread',
        'pan rallado' => 'breadcrumbs',
        'azucar moreno' => 'brown sugar',
        'condimento cajun' => 'cajun seasoning',
        'alcaparras' => 'capers',
        'anacardos' => 'cashews',
        'chocolate' => 'chocolate',
        'leche de coco' => 'coconut milk',
        'aceite de coco' => 'coconut oil',
        'cafe' => 'coffee',
        'maiz' => 'corn',
        'harina de maiz' => 'corn flour',
        'maicena' => 'cornstarch',
        'dátiles' => 'dates',
        'salsa de pescado' => 'fish sauce',
        'harina' => 'flour',
        'ajo' => 'garlic',
        'ajo en polvo' => 'garlic powder',
        'miel' => 'honey',
        'salsa picante' => 'hot sauce',
        'ketchup' => 'ketchup',
        'sirope de arce' => 'maple syrup',
        'mayonesa' => 'mayonnaise',
        'aceite de oliva' => 'olive oil',
        'aceitunas' => 'olives',
        'pickles' => 'pickles',
        'cacahuetes' => 'peanuts',
        'piñones' => 'pine nuts',
        'pistachos' => 'pistachios',
        'paté' => 'pate',
        'paté de hígado' => 'liver pate',
        'azucar' => 'sugar',
        'sal' => 'salt',
        'aceite vegetal' => 'vegetable oil',
        'aceite de sésamo' => 'sesame oil',
        'vinagre de vino tinto' => 'red wine vinegar',
        'vinagre de vino blanco' => 'white wine vinegar',
        'pure de tomate' => 'tomato puree',
        'salsa de tomate' => 'tomato sauce',
        'pasta de ajo' => 'garlic paste',
        'pasta de jengibre' => 'ginger paste',

        'salsa de soja' => 'soy sauce',
        'salsa worcestershire' => 'worcestershire sauce',
        'vinagre' => 'vinegar',
        'gelatina' => 'gelatin',
        'caldo' => 'broth',


    ],

    'categorias' => [
        'beef' => 'ternera',
        'breakfast' => 'desayuno',
        'chicken' => 'pollo',
        'dessert' => 'postre',
        'goat' => 'cabra',
        'lamb' => 'cordero',
        'miscellaneous' => 'misceláneo',
        'pasta' => 'pasta',
        'pork' => 'cerdo',
        'seafood' => 'mariscos',
        'side' => 'acompañamiento',
        'starter' => 'entrante',
        'vegan' => 'vegano',
        'vegetarian' => 'vegetariano',
    ],

    'areas' => [
        'american' => 'estadounidense',
        'british' => 'británica',
        'canadian' => 'canadiense',
        'chinese' => 'china',
        'croatian' => 'croata',
        'dutch' => 'holandesa',
        'egyptian' => 'egipcia',
        'french' => 'francesa',
        'greek' => 'griega',
        'indian' => 'india',
        'irish' => 'irlandesa',
        'italian' => 'italiana',
        'jamaican' => 'jamaicana',
        'japanese' => 'japonesa',
        'kenyan' => 'keniana',
        'malaysian' => 'malasia',
        'mexican' => 'mexicana',
        'moroccan' => 'marroquí',
        'polish' => 'polaca',
        'portuguese' => 'portuguesa',
        'russian' => 'rusa',
        'spanish' => 'española',
        'thai' => 'tailandesa',
        'tunisian' => 'tunecina',
        'turkish' => 'turca',
        'unknown' => 'desconocida',
        'vietnamese' => 'vietnamita',
    ],
];
